apiVersion: v1
kind: Secret
metadata:
  name: kguard-ai-secret
  labels:
    app: kguard-ai
    app.kubernetes.io/name: kguard-ai
    app.kubernetes.io/part-of: k-guard
type: Opaque
stringData:
  ELASTICSEARCH_USERNAME: "replace-me"
  ELASTICSEARCH_PASSWORD: "replace-me"
