apiVersion: v1
kind: Secret
metadata:
  name: kguard-ai-secrets
  namespace: k-guard
type: Opaque
stringData:
  KGUARD_AI_ELASTICSEARCH_USERNAME: "set-me"
  KGUARD_AI_ELASTICSEARCH_PASSWORD: "set-me"
