apiVersion: v1
kind: Service
metadata:
  name: kguard-ai
  labels:
    app: kguard-ai
    app.kubernetes.io/name: kguard-ai
    app.kubernetes.io/part-of: k-guard
spec:
  selector:
    app: kguard-ai
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP
